### ISSUE TITLE
Streaming a live terminal window

### ISSUE THREAD

**Issue by ndench** [anishathalye/seashells#10]
Is it possile to stream a live terminal window not just the output of a single command?

**Comment by anishathalye** [comment]
Try `bash | seashells` ?

**Comment by ndench** [comment]
Thanks, that works pretty well, except it only shows the output of every command and not the prompt and the command that you're typing. I actually found this that works great though: https://www.reddit.com/r/commandline/comments/263afq/bashtmux_pipe_the_output_of_a_detached_tmux/

You pipe tmux into a file with `pipe-pane -o  'cat /tmp/tmuxpipe'`, then you can `tail -f /tmp/tmuxpipe | seashells` and it works great.

Thanks for you help.
