### ISSUE TITLE
Error 502 Bad Gateway from seashells.io

### ISSUE THREAD

**Issue by possibly-wrong** [anishathalye/seashells#19]
First, thanks for a great and very useful tool. I noticed (approximately yesterday morning) that accessing https://seashells.io yields Error 502 Bad Gateway (nginx/1.10.3). I initially noticed this accessing my most recent log URL [https://seashells.io/v/XG5bEUy5](https://seashells.io/v/XG5bEUy5), but with the same error from the top-level site, tested from multiple computers from a couple of separate ISPs, suggests that a server is simply down? Let me know if I can provide more detailed information.

**Comment by anishathalye** [comment]
Oops; fixed now.
