### ISSUE TITLE
Make it on private Cloud server insted seashells.io

### ISSUE THREAD

**Issue by yahyaahrika** [anishathalye/seashells#20]
I try to make own server show the Output in Realtime like 
CLI : *"Asterisk -rvvv"*
Every time send new information 
Could you share with asf Code are in Server (seashells.io) ?

**Comment by anishathalye** [comment]
I think this is a dupe of #2. It is now on my to-do list to open-source the server, but it's not a high-priority thing, so it hasn't happened yet.
