### ISSUE TITLE
Is seashells down? Is it going to come back?

### ISSUE THREAD

**Issue by esthon** [anishathalye/seashells#21]
It is a very good service! I have used it a lot, but today it is saying :

502 Bad Gateway
nginx/1.10.3

**Comment by anishathalye** [comment]
Sorry, there was an issue with the hosting infrastructure this morning. I got an alert on my phone when it went down, but I didn't have access to a computer until now to sort it out. It's back up now.

Just out of curiosity, how do you use seashells? If you're willing to share a bit of info on your use case, could you email me a short description at aathalye@me.com? I'm considering spending some time revamping the service, so I'm trying to better understand how people are using it.

**Comment by esthon** [comment]
I will send you a message, thanks very much!
