### ISSUE TITLE
Breaks with tqdm

### ISSUE THREAD

**Issue by joshuagruenstein** [anishathalye/seashells#3]
For some reason, tqdm and seashells do not play nice.  This is sad, as tqdm is nice for monitoring large training batches.

**Comment by mdraw** [comment]
I assume with "do not play nice" you mean that tqdm output does not appear on your seashells page. If you just run

    $ somecommand | seashells

only the `stdout` stream is piped to seashells. By default tqdm does not write to `stdout` but to `stderr`, so to make your progress bars appear on `seashells`, you will either have to pass `file=sys.stdout` to tqdm, for example:
```python
import sys
import time
from tqdm import tqdm
for _ in tqdm(range(100), file=sys.stdout)):
    time.sleep(0.1)
```
or alternatively, pipe both `stdout` and `stderr` to `seashells` in your shell:

    $ somecommand 2>&1 | seashells

**Comment by joshuagruenstein** [comment]
Thank you, this is helpful.
