### ISSUE TITLE
Seashells client ported in node.

### ISSUE THREAD

**Issue by roccomuso** [anishathalye/seashells#4]
I made an unoffical client for Node.js, [@roccomuso/seashells](https://github.com/roccomuso/seashells), available for download also on [npm](https://npmjs.com/package/seashells). ;)

**Comment by anishathalye** [comment]
Cool! I added it to this list here: https://github.com/anishathalye/seashells#other-clients

**Comment by roccomuso** [comment]
Nice. Thanks ;)
