### ISSUE TITLE
Port written in golang

### ISSUE THREAD

**Issue by hans-strudle** [anishathalye/seashells#6]
First off I just want to say thanks as I have been using seashells almost every day over the past month both at work and at home and it is absolutely awesome. Also I and ended up writing a golang port ([hans-strudle/seashells](https://github.com/hans-strudle/seashells) if anyone is interested. Thanks!

**Comment by anishathalye** [comment]
Whoa, glad to hear you're finding it useful :)

Wanna send me a PR to add your port to [the list](https://github.com/anishathalye/seashells#other-clients)?

**Comment by hans-strudle** [comment]
Just sent the PR

**Comment by anishathalye** [comment]
Thanks!
