### ISSUE TITLE
Windows Socket Error

### ISSUE THREAD

**Issue by Scrxtchy** [anishathalye/seashells#9]
When using Seashells, the following is output to the console
```
echo 'test' | seashells
serving at https://seashells.io/v/rgPwbMmV
socket error: [WinError 10038] An operation was attempted on something that is not a socket
'test'
```

Using 0.1.2

**Comment by anishathalye** [comment]
Seashells uses [select(2)](http://man7.org/linux/man-pages/man2/select.2.html), which works for Linux/macOS, but is not supported on Windows.

I don't know if there's a clean way to fix this for Windows without too much effort. It would definitely be nice to fix this.
